package com.kingway.model;

// Generated 2010-11-9 23:20:42 by Hibernate Tools 3.3.0.GA

/**
 * CheckUpdateUserModuleViewId generated by hbm2java
 */
public class CheckUpdateUserModuleViewId implements java.io.Serializable {

	private long userId;
	private long userModuleId;
	private int ignoreByUser;
	private long contentId;

	public CheckUpdateUserModuleViewId() {
	}

	public CheckUpdateUserModuleViewId(long userId, long userModuleId,
			int ignoreByUser,long contentId) {
		this.userId = userId;
		this.userModuleId = userModuleId;
		this.ignoreByUser = ignoreByUser;
		this.contentId=contentId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public int getIgnoreByUser() {
		return this.ignoreByUser;
	}

	public void setIgnoreByUser(int ignoreByUser) {
		this.ignoreByUser = ignoreByUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CheckUpdateUserModuleViewId))
			return false;
		CheckUpdateUserModuleViewId castOther = (CheckUpdateUserModuleViewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getUserModuleId() == castOther.getUserModuleId())
				&& (this.getIgnoreByUser() == castOther.getIgnoreByUser()
						&& (this.getContentId() == castOther.getContentId()));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getUserModuleId();
		result = 37 * result + this.getIgnoreByUser();
		
		return result;
	}

	public void setContentId(long contentId) {
		this.contentId = contentId;
	}

	public long getContentId() {
		return contentId;
	}

}
