package com.kingway.model;

// Generated 2010-11-9 23:20:42 by Hibernate Tools 3.3.0.GA

/**
 * CheckUpdateUserModuleView generated by hbm2java
 */
public class CheckUpdateUserModuleView implements java.io.Serializable {

	private CheckUpdateUserModuleViewId id;

	public CheckUpdateUserModuleView() {
	}

	public CheckUpdateUserModuleView(CheckUpdateUserModuleViewId id) {
		this.id = id;
	}

	public CheckUpdateUserModuleViewId getId() {
		return this.id;
	}

	public void setId(CheckUpdateUserModuleViewId id) {
		this.id = id;
	}

}
