package com.kingway.model;

// Generated 2010-10-15 10:27:00 by Hibernate Tools 3.3.0.GA

/**
 * CheckUpdateViewId generated by hbm2java
 */
public class CheckUpdateViewId implements java.io.Serializable {

	private long sendId;
	private long bufferId;
	private long userModuleId;
	private long moduleId;

	public CheckUpdateViewId() {
	}

	public CheckUpdateViewId(long sendId, long bufferId, long userModuleId,
			long moduleId) {
		this.sendId = sendId;
		this.bufferId = bufferId;
		this.userModuleId = userModuleId;
		this.moduleId = moduleId;
	}

	public long getSendId() {
		return this.sendId;
	}

	public void setSendId(long sendId) {
		this.sendId = sendId;
	}

	public long getBufferId() {
		return this.bufferId;
	}

	public void setBufferId(long bufferId) {
		this.bufferId = bufferId;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CheckUpdateViewId))
			return false;
		CheckUpdateViewId castOther = (CheckUpdateViewId) other;

		return (this.getSendId() == castOther.getSendId())
				&& (this.getBufferId() == castOther.getBufferId())
				&& (this.getUserModuleId() == castOther.getUserModuleId())
				&& (this.getModuleId() == castOther.getModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSendId();
		result = 37 * result + (int) this.getBufferId();
		result = 37 * result + (int) this.getUserModuleId();
		result = 37 * result + (int) this.getModuleId();
		return result;
	}

}
