package com.kingway.model;

// Generated 2010-10-15 10:27:00 by Hibernate Tools 3.3.0.GA

/**
 * CheckUpdateView generated by hbm2java
 */
public class CheckUpdateView implements java.io.Serializable {

	private CheckUpdateViewId id;

	public CheckUpdateView() {
	}

	public CheckUpdateView(CheckUpdateViewId id) {
		this.id = id;
	}

	public CheckUpdateViewId getId() {
		return this.id;
	}

	public void setId(CheckUpdateViewId id) {
		this.id = id;
	}

}
