package com.kingway.model;

// Generated 2010-11-28 21:08:00 by Hibernate Tools 3.3.0.GA

/**
 * ContentNeedToBeSendView generated by hbm2java
 */
public class ContentNeedToBeSendView implements java.io.Serializable {

	private ContentNeedToBeSendViewId id;

	public ContentNeedToBeSendView() {
	}

	public ContentNeedToBeSendView(ContentNeedToBeSendViewId id) {
		this.id = id;
	}

	public ContentNeedToBeSendViewId getId() {
		return this.id;
	}

	public void setId(ContentNeedToBeSendViewId id) {
		this.id = id;
	}

}
