package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContentBuffer generated by hbm2java
 */
public class ContentBuffer implements java.io.Serializable {

	private Long bufferId;
	private ModuleInfo moduleInfo;
	private String content;
	private Date updateTime = new Date();;
	private int updateType = 0;
	private Set<ContentReceiver> contentReceivers = new HashSet<ContentReceiver>(
			0);

	public ContentBuffer() {
	}

	public ContentBuffer(ModuleInfo moduleInfo, String content,
			Date updateTime, int updateType) {
		this.moduleInfo = moduleInfo;
		this.content = content;
		this.updateTime = updateTime;
		this.updateType = updateType;
	}

	public ContentBuffer(ModuleInfo moduleInfo, String content,
			Date updateTime, int updateType,
			Set<ContentReceiver> contentReceivers) {
		this.moduleInfo = moduleInfo;
		this.content = content;
		this.updateTime = updateTime;
		this.updateType = updateType;
		this.contentReceivers = contentReceivers;
	}

	public Long getBufferId() {
		return this.bufferId;
	}

	public void setBufferId(Long bufferId) {
		this.bufferId = bufferId;
	}

	public ModuleInfo getModuleInfo() {
		return this.moduleInfo;
	}

	public void setModuleInfo(ModuleInfo moduleInfo) {
		this.moduleInfo = moduleInfo;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getUpdateType() {
		return this.updateType;
	}

	public void setUpdateType(int updateType) {
		this.updateType = updateType;
	}

	public Set<ContentReceiver> getContentReceivers() {
		return this.contentReceivers;
	}

	public void setContentReceivers(Set<ContentReceiver> contentReceivers) {
		this.contentReceivers = contentReceivers;
	}

}
