package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * ContentReceiver generated by hbm2java
 */
public class ContentReceiver implements java.io.Serializable {

	private Long sendId;
	private ContentBuffer contentBuffer;
	private UserModuleInfo userModuleInfo;
	private int sendType;

	public ContentReceiver() {
	}

	public ContentReceiver(ContentBuffer contentBuffer,
			UserModuleInfo userModuleInfo, int sendType) {
		this.contentBuffer = contentBuffer;
		this.userModuleInfo = userModuleInfo;
		this.sendType = sendType;
	}

	public Long getSendId() {
		return this.sendId;
	}

	public void setSendId(Long sendId) {
		this.sendId = sendId;
	}

	public ContentBuffer getContentBuffer() {
		return this.contentBuffer;
	}

	public void setContentBuffer(ContentBuffer contentBuffer) {
		this.contentBuffer = contentBuffer;
	}

	public UserModuleInfo getUserModuleInfo() {
		return this.userModuleInfo;
	}

	public void setUserModuleInfo(UserModuleInfo userModuleInfo) {
		this.userModuleInfo = userModuleInfo;
	}

	public int getSendType() {
		return this.sendType;
	}

	public void setSendType(int sendType) {
		this.sendType = sendType;
	}

}
