package com.kingway.model;

// Generated 2010-10-1 15:00:04 by Hibernate Tools 3.3.0.GA

/**
 * ContentReceiverView generated by hbm2java
 */
public class ContentReceiverView implements java.io.Serializable {

	private ContentReceiverViewId id;

	public ContentReceiverView() {
	}

	public ContentReceiverView(ContentReceiverViewId id) {
		this.id = id;
	}

	public ContentReceiverViewId getId() {
		return this.id;
	}

	public void setId(ContentReceiverViewId id) {
		this.id = id;
	}

}
