package com.kingway.model;

// Generated 2010-10-1 15:00:04 by Hibernate Tools 3.3.0.GA

/**
 * ContentReceiverViewId generated by hbm2java
 */
public class ContentReceiverViewId implements java.io.Serializable {

	private int sendType;
	private long userId;
	private long sendId;

	public ContentReceiverViewId() {
	}

	public ContentReceiverViewId(int sendType, long userId, long sendId) {
		this.sendType = sendType;
		this.userId = userId;
		this.sendId = sendId;
	}

	public int getSendType() {
		return this.sendType;
	}

	public void setSendType(int sendType) {
		this.sendType = sendType;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getSendId() {
		return this.sendId;
	}

	public void setSendId(long sendId) {
		this.sendId = sendId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContentReceiverViewId))
			return false;
		ContentReceiverViewId castOther = (ContentReceiverViewId) other;

		return (this.getSendType() == castOther.getSendType())
				&& (this.getUserId() == castOther.getUserId())
				&& (this.getSendId() == castOther.getSendId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSendType();
		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getSendId();
		return result;
	}

}
