package com.kingway.model;

// Generated 2011-1-23 9:52:10 by Hibernate Tools 3.3.0.GA

/**
 * Failwebaddresstest generated by hbm2java
 */
public class Failwebaddresstest implements java.io.Serializable {

	private FailwebaddresstestId id;

	public Failwebaddresstest() {
	}

	public Failwebaddresstest(FailwebaddresstestId id) {
		this.id = id;
	}

	public FailwebaddresstestId getId() {
		return this.id;
	}

	public void setId(FailwebaddresstestId id) {
		this.id = id;
	}

}
