package com.kingway.model;

// Generated 2011-1-23 9:52:10 by Hibernate Tools 3.3.0.GA

/**
 * FailwebaddresstestId generated by hbm2java
 */
public class FailwebaddresstestId implements java.io.Serializable {

	private String webAddress;
	private int failTimes;

	public FailwebaddresstestId() {
	}

	public FailwebaddresstestId(String webAddress, int failTimes) {
		this.webAddress = webAddress;
		this.failTimes = failTimes;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public int getFailTimes() {
		return this.failTimes;
	}

	public void setFailTimes(int failTimes) {
		this.failTimes = failTimes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FailwebaddresstestId))
			return false;
		FailwebaddresstestId castOther = (FailwebaddresstestId) other;

		return ((this.getWebAddress() == castOther.getWebAddress()) || (this
				.getWebAddress() != null
				&& castOther.getWebAddress() != null && this.getWebAddress()
				.equals(castOther.getWebAddress())))
				&& (this.getFailTimes() == castOther.getFailTimes());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		result = 37 * result + this.getFailTimes();
		return result;
	}

}
