package com.kingway.model;

// Generated 2011-1-23 9:52:10 by Hibernate Tools 3.3.0.GA

/**
 * FriendsInfo generated by hbm2java
 */
public class FriendsInfo implements java.io.Serializable {

	private Long id;
	private UserInfo userInfo;
	private long userId;
	private int friendState;
	private String friendInfo;
	private Long subgroupId;

	public FriendsInfo() {
	}

	public FriendsInfo(UserInfo userInfo, long userId, int friendState) {
		this.userInfo = userInfo;
		this.userId = userId;
		this.friendState = friendState;
	}

	public FriendsInfo(UserInfo userInfo, long userId, int friendState,
			String friendInfo, Long subgroupId) {
		this.userInfo = userInfo;
		this.userId = userId;
		this.friendState = friendState;
		this.friendInfo = friendInfo;
		this.subgroupId = subgroupId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public int getFriendState() {
		return this.friendState;
	}

	public void setFriendState(int friendState) {
		this.friendState = friendState;
	}

	public String getFriendInfo() {
		return this.friendInfo;
	}

	public void setFriendInfo(String friendInfo) {
		this.friendInfo = friendInfo;
	}

	public Long getSubgroupId() {
		return this.subgroupId;
	}

	public void setSubgroupId(Long subgroupId) {
		this.subgroupId = subgroupId;
	}

}
