package com.kingway.model;

// Generated 2010-10-25 22:38:40 by Hibernate Tools 3.3.0.GA

/**
 * MailNeedToBeSendView generated by hbm2java
 */
public class MailNeedToBeSendView implements java.io.Serializable {

	private MailNeedToBeSendViewId id;

	public MailNeedToBeSendView() {
	}

	public MailNeedToBeSendView(MailNeedToBeSendViewId id) {
		this.id = id;
	}

	public MailNeedToBeSendViewId getId() {
		return this.id;
	}

	public void setId(MailNeedToBeSendViewId id) {
		this.id = id;
	}

}
