package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * MessageNeedToBeSendView generated by hbm2java
 */
public class MessageNeedToBeSendView implements java.io.Serializable {

	private MessageNeedToBeSendViewId id;

	public MessageNeedToBeSendView() {
	}

	public MessageNeedToBeSendView(MessageNeedToBeSendViewId id) {
		this.id = id;
	}

	public MessageNeedToBeSendViewId getId() {
		return this.id;
	}

	public void setId(MessageNeedToBeSendViewId id) {
		this.id = id;
	}

}
