package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * MessageNeedToBeSendViewId generated by hbm2java
 */
public class MessageNeedToBeSendViewId implements java.io.Serializable {

	private Integer monitorType;
	private String userName;
	private String content;
	private Date updateTime;
	private String phone;
	private String userModuleName;
	private String websiteName;
	private long sendId;
	private int maxReceiveNum;
	private long receiveId;
	private int receiveType;

	public MessageNeedToBeSendViewId() {
	}

	public MessageNeedToBeSendViewId(String userName, String content,
			Date updateTime, String userModuleName, String websiteName,
			long sendId, int maxReceiveNum, long receiveId, int receiveType) {
		this.userName = userName;
		this.content = content;
		this.updateTime = updateTime;
		this.userModuleName = userModuleName;
		this.websiteName = websiteName;
		this.sendId = sendId;
		this.maxReceiveNum = maxReceiveNum;
		this.receiveId = receiveId;
		this.receiveType = receiveType;
	}

	public MessageNeedToBeSendViewId(Integer monitorType, String userName,
			String content, Date updateTime, String phone,
			String userModuleName, String websiteName, long sendId,
			int maxReceiveNum, long receiveId, int receiveType) {
		this.monitorType = monitorType;
		this.userName = userName;
		this.content = content;
		this.updateTime = updateTime;
		this.phone = phone;
		this.userModuleName = userModuleName;
		this.websiteName = websiteName;
		this.sendId = sendId;
		this.maxReceiveNum = maxReceiveNum;
		this.receiveId = receiveId;
		this.receiveType = receiveType;
	}

	public Integer getMonitorType() {
		return this.monitorType;
	}

	public void setMonitorType(Integer monitorType) {
		this.monitorType = monitorType;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUserModuleName() {
		return this.userModuleName;
	}

	public void setUserModuleName(String userModuleName) {
		this.userModuleName = userModuleName;
	}

	public String getWebsiteName() {
		return this.websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public long getSendId() {
		return this.sendId;
	}

	public void setSendId(long sendId) {
		this.sendId = sendId;
	}

	public int getMaxReceiveNum() {
		return this.maxReceiveNum;
	}

	public void setMaxReceiveNum(int maxReceiveNum) {
		this.maxReceiveNum = maxReceiveNum;
	}

	public long getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(long receiveId) {
		this.receiveId = receiveId;
	}

	public int getReceiveType() {
		return this.receiveType;
	}

	public void setReceiveType(int receiveType) {
		this.receiveType = receiveType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessageNeedToBeSendViewId))
			return false;
		MessageNeedToBeSendViewId castOther = (MessageNeedToBeSendViewId) other;

		return ((this.getMonitorType() == castOther.getMonitorType()) || (this
				.getMonitorType() != null
				&& castOther.getMonitorType() != null && this.getMonitorType()
				.equals(castOther.getMonitorType())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getContent() == castOther.getContent()) || (this
						.getContent() != null
						&& castOther.getContent() != null && this.getContent()
						.equals(castOther.getContent())))
				&& ((this.getUpdateTime() == castOther.getUpdateTime()) || (this
						.getUpdateTime() != null
						&& castOther.getUpdateTime() != null && this
						.getUpdateTime().equals(castOther.getUpdateTime())))
				&& ((this.getPhone() == castOther.getPhone()) || (this
						.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone()
						.equals(castOther.getPhone())))
				&& ((this.getUserModuleName() == castOther.getUserModuleName()) || (this
						.getUserModuleName() != null
						&& castOther.getUserModuleName() != null && this
						.getUserModuleName().equals(
								castOther.getUserModuleName())))
				&& ((this.getWebsiteName() == castOther.getWebsiteName()) || (this
						.getWebsiteName() != null
						&& castOther.getWebsiteName() != null && this
						.getWebsiteName().equals(castOther.getWebsiteName())))
				&& (this.getSendId() == castOther.getSendId())
				&& (this.getMaxReceiveNum() == castOther.getMaxReceiveNum())
				&& (this.getReceiveId() == castOther.getReceiveId())
				&& (this.getReceiveType() == castOther.getReceiveType());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMonitorType() == null ? 0 : this.getMonitorType()
						.hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37
				* result
				+ (getUpdateTime() == null ? 0 : this.getUpdateTime()
						.hashCode());
		result = 37 * result
				+ (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37
				* result
				+ (getUserModuleName() == null ? 0 : this.getUserModuleName()
						.hashCode());
		result = 37
				* result
				+ (getWebsiteName() == null ? 0 : this.getWebsiteName()
						.hashCode());
		result = 37 * result + (int) this.getSendId();
		result = 37 * result + this.getMaxReceiveNum();
		result = 37 * result + (int) this.getReceiveId();
		result = 37 * result + this.getReceiveType();
		return result;
	}

}
