package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * ModuleNeedToBeUpdateViewId generated by hbm2java
 */
public class ModuleNeedToBeUpdateViewId implements java.io.Serializable {

	private String webAddress;
	private long moduleId;
	private String path;
	private double lastTime;
	private String updateContent;

	public ModuleNeedToBeUpdateViewId() {
	}

	public ModuleNeedToBeUpdateViewId(String webAddress, long moduleId,
			double lastTime, String updateContent) {
		this.webAddress = webAddress;
		this.moduleId = moduleId;
		this.lastTime = lastTime;
		this.updateContent = updateContent;
	}

	public ModuleNeedToBeUpdateViewId(String webAddress, long moduleId,
			String path, double lastTime, String updateContent) {
		this.webAddress = webAddress;
		this.moduleId = moduleId;
		this.path = path;
		this.lastTime = lastTime;
		this.updateContent = updateContent;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public double getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(double lastTime) {
		this.lastTime = lastTime;
	}

	public String getUpdateContent() {
		return this.updateContent;
	}

	public void setUpdateContent(String updateContent) {
		this.updateContent = updateContent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModuleNeedToBeUpdateViewId))
			return false;
		ModuleNeedToBeUpdateViewId castOther = (ModuleNeedToBeUpdateViewId) other;

		return ((this.getWebAddress() == castOther.getWebAddress()) || (this
				.getWebAddress() != null
				&& castOther.getWebAddress() != null && this.getWebAddress()
				.equals(castOther.getWebAddress())))
				&& (this.getModuleId() == castOther.getModuleId())
				&& ((this.getPath() == castOther.getPath()) || (this.getPath() != null
						&& castOther.getPath() != null && this.getPath()
						.equals(castOther.getPath())))
				&& (this.getLastTime() == castOther.getLastTime())
				&& ((this.getUpdateContent() == castOther.getUpdateContent()) || (this
						.getUpdateContent() != null
						&& castOther.getUpdateContent() != null && this
						.getUpdateContent()
						.equals(castOther.getUpdateContent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		result = 37 * result + (int) this.getModuleId();
		result = 37 * result
				+ (getPath() == null ? 0 : this.getPath().hashCode());
		result = 37 * result + (int) this.getLastTime();
		result = 37
				* result
				+ (getUpdateContent() == null ? 0 : this.getUpdateContent()
						.hashCode());
		return result;
	}

}
