package com.kingway.model;

// Generated 2010-10-15 9:24:51 by Hibernate Tools 3.3.0.GA

/**
 * ModuleInfoShowView generated by hbm2java
 */
public class ModuleInfoShowView implements java.io.Serializable {

	private ModuleInfoShowViewId id;

	public ModuleInfoShowView() {
	}

	public ModuleInfoShowView(ModuleInfoShowViewId id) {
		this.id = id;
	}

	public ModuleInfoShowViewId getId() {
		return this.id;
	}

	public void setId(ModuleInfoShowViewId id) {
		this.id = id;
	}

}
