package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ModuleInfo generated by hbm2java
 */
public class ModuleInfo implements java.io.Serializable {
	private String defineSource;
	private Long moduleId;
	private MonitorWebInfo monitorWebInfo;
	private String modulePath;
	private int failTimes = 0;
	private int enable = 1;
	private String updateContent;
	private String rssContent;
	private Long userCount;
	private Set<ContentBuffer> contentBuffers = new HashSet<ContentBuffer>(0);
	private Set<UserModuleInfo> userModuleInfos = new HashSet<UserModuleInfo>(0);

	public ModuleInfo() {
	}

	public ModuleInfo(MonitorWebInfo monitorWebInfo, int failTimes, int enable,
			String updateContent) {
		this.monitorWebInfo = monitorWebInfo;
		this.failTimes = failTimes;
		this.enable = enable;
		this.updateContent = updateContent;
	}

	public ModuleInfo(MonitorWebInfo monitorWebInfo, String modulePath,
			int failTimes, int enable, String updateContent, Long userCount,
			Set<ContentBuffer> contentBuffers,
			Set<UserModuleInfo> userModuleInfos) {
		this.monitorWebInfo = monitorWebInfo;
		this.modulePath = modulePath;
		this.failTimes = failTimes;
		this.enable = enable;
		this.updateContent = updateContent;
		this.userCount = userCount;
		this.contentBuffers = contentBuffers;
		this.userModuleInfos = userModuleInfos;
	}

	public Long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}

	public MonitorWebInfo getMonitorWebInfo() {
		return this.monitorWebInfo;
	}

	public void setMonitorWebInfo(MonitorWebInfo monitorWebInfo) {
		this.monitorWebInfo = monitorWebInfo;
	}

	public String getModulePath() {
		return this.modulePath;
	}

	public void setModulePath(String modulePath) {
		this.modulePath = modulePath;
	}

	public int getFailTimes() {
		return this.failTimes;
	}

	public void setFailTimes(int failTimes) {
		this.failTimes = failTimes;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public String getUpdateContent() {
		return this.updateContent;
	}

	public void setUpdateContent(String updateContent) {
		this.updateContent = updateContent;
	}

	public Long getUserCount() {
		return this.userCount;
	}

	public void setUserCount(Long userCount) {
		this.userCount = userCount;
	}

	public Set<ContentBuffer> getContentBuffers() {
		return this.contentBuffers;
	}

	public void setContentBuffers(Set<ContentBuffer> contentBuffers) {
		this.contentBuffers = contentBuffers;
	}

	public Set<UserModuleInfo> getUserModuleInfos() {
		return this.userModuleInfos;
	}

	public void setUserModuleInfos(Set<UserModuleInfo> userModuleInfos) {
		this.userModuleInfos = userModuleInfos;
	}

	public void setRssContent(String rssContent) {
		this.rssContent = rssContent;
	}

	public String getRssContent() {
		return rssContent;
	}

	public void setDefineSource(String defineSource) {
		this.defineSource = defineSource;
	}

	public String getDefineSource() {
		return defineSource;
	}

}
