package com.kingway.model;

// Generated 2011-3-12 23:18:01 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * ModuleHistoyNumViewId generated by hbm2java
 */
public class ModuleHistoyNumViewId implements java.io.Serializable {

	private BigDecimal num;
	private long userModuleId;

	public ModuleHistoyNumViewId() {
	}

	public ModuleHistoyNumViewId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public ModuleHistoyNumViewId(BigDecimal num, long userModuleId) {
		this.num = num;
		this.userModuleId = userModuleId;
	}

	public BigDecimal getNum() {
		return this.num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModuleHistoyNumViewId))
			return false;
		ModuleHistoyNumViewId castOther = (ModuleHistoyNumViewId) other;

		return ((this.getNum() == castOther.getNum()) || (this.getNum() != null
				&& castOther.getNum() != null && this.getNum().equals(
				castOther.getNum())))
				&& (this.getUserModuleId() == castOther.getUserModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNum() == null ? 0 : this.getNum().hashCode());
		result = 37 * result + (int) this.getUserModuleId();
		return result;
	}

}
