package com.kingway.model;

// Generated 2010-10-18 22:22:50 by Hibernate Tools 3.3.0.GA

/**
 * ModulesLinkView generated by hbm2java
 */
public class ModulesLinkView implements java.io.Serializable {

	private ModulesLinkViewId id;

	public ModulesLinkView() {
	}

	public ModulesLinkView(ModulesLinkViewId id) {
		this.id = id;
	}

	public ModulesLinkViewId getId() {
		return this.id;
	}

	public void setId(ModulesLinkViewId id) {
		this.id = id;
	}

}
