package com.kingway.model;

// Generated 2011-3-12 23:18:01 by Hibernate Tools 3.3.0.GA

/**
 * ModuleHistoyNumView generated by hbm2java
 */
public class ModuleHistoyNumView implements java.io.Serializable {

	private ModuleHistoyNumViewId id;

	public ModuleHistoyNumView() {
	}

	public ModuleHistoyNumView(ModuleHistoyNumViewId id) {
		this.id = id;
	}

	public ModuleHistoyNumViewId getId() {
		return this.id;
	}

	public void setId(ModuleHistoyNumViewId id) {
		this.id = id;
	}

}
