package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * ModuleNeedToBeUpdateView generated by hbm2java
 */
public class ModuleNeedToBeUpdateView implements java.io.Serializable {

	private ModuleNeedToBeUpdateViewId id;

	public ModuleNeedToBeUpdateView() {
	}

	public ModuleNeedToBeUpdateView(ModuleNeedToBeUpdateViewId id) {
		this.id = id;
	}

	public ModuleNeedToBeUpdateViewId getId() {
		return this.id;
	}

	public void setId(ModuleNeedToBeUpdateViewId id) {
		this.id = id;
	}

}
