package com.kingway.model;

// Generated 2010-10-18 22:22:50 by Hibernate Tools 3.3.0.GA

/**
 * ModulesLinkViewId generated by hbm2java
 */
public class ModulesLinkViewId implements java.io.Serializable {

	private String userName;
	private String phone;
	private long receiveId;
	private long userModuleId;

	public ModulesLinkViewId() {
	}

	public ModulesLinkViewId(String userName, long receiveId, long userModuleId) {
		this.userName = userName;
		this.receiveId = receiveId;
		this.userModuleId = userModuleId;
	}

	public ModulesLinkViewId(String userName, String phone, long receiveId,
			long userModuleId) {
		this.userName = userName;
		this.phone = phone;
		this.receiveId = receiveId;
		this.userModuleId = userModuleId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public long getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(long receiveId) {
		this.receiveId = receiveId;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModulesLinkViewId))
			return false;
		ModulesLinkViewId castOther = (ModulesLinkViewId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this
				.getUserName() != null
				&& castOther.getUserName() != null && this.getUserName()
				.equals(castOther.getUserName())))
				&& ((this.getPhone() == castOther.getPhone()) || (this
						.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone()
						.equals(castOther.getPhone())))
				&& (this.getReceiveId() == castOther.getReceiveId())
				&& (this.getUserModuleId() == castOther.getUserModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (int) this.getReceiveId();
		result = 37 * result + (int) this.getUserModuleId();
		return result;
	}

}
