package com.kingway.model;

// Generated 2010-10-15 9:24:51 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * ModuleInfoShowViewId generated by hbm2java
 */
public class ModuleInfoShowViewId implements java.io.Serializable {

	private long userId;
	private String websiteName;
	private String userModuleName;
	private Date updateTime;
	private String webAddress;
	private long userModuleId;
	private Integer accessType;
	private String userModuleStyle;
	private Long subgroupId;
	private int enable;
	private String updateContent;
	private long contentId;
	private long moduleId;
	private int contentType;
	private String headCssAndScript;
	private String bodyCssAndScript;
	private String unCheckPaths;
	private int ignoreByUser;

	public ModuleInfoShowViewId() {
	}

	public ModuleInfoShowViewId(long userId, String websiteName,
			String userModuleName, Date updateTime, String webAddress,
			long userModuleId, int enable, String updateContent,
			long contentId, long moduleId, int contentType) {
		this.userId = userId;
		this.websiteName = websiteName;
		this.userModuleName = userModuleName;
		this.updateTime = updateTime;
		this.webAddress = webAddress;
		this.userModuleId = userModuleId;
		this.enable = enable;
		this.updateContent = updateContent;
		this.contentId = contentId;
		this.moduleId = moduleId;
		this.contentType = contentType;
	}

	public ModuleInfoShowViewId(long userId, String websiteName,
			String userModuleName, Date updateTime, String webAddress,
			long userModuleId, Integer accessType, String userModuleStyle,
			Long subgroupId, int enable, String updateContent, long contentId,
			long moduleId, int contentType, String headCssAndScript,
			String bodyCssAndScript, String unCheckPaths) {
		this.userId = userId;
		this.websiteName = websiteName;
		this.userModuleName = userModuleName;
		this.updateTime = updateTime;
		this.webAddress = webAddress;
		this.userModuleId = userModuleId;
		this.accessType = accessType;
		this.userModuleStyle = userModuleStyle;
		this.subgroupId = subgroupId;
		this.enable = enable;
		this.updateContent = updateContent;
		this.contentId = contentId;
		this.moduleId = moduleId;
		this.contentType = contentType;
		this.headCssAndScript = headCssAndScript;
		this.bodyCssAndScript = bodyCssAndScript;
		this.unCheckPaths = unCheckPaths;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getWebsiteName() {
		return this.websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public String getUserModuleName() {
		return this.userModuleName;
	}

	public void setUserModuleName(String userModuleName) {
		this.userModuleName = userModuleName;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public Integer getAccessType() {
		return this.accessType;
	}

	public void setAccessType(Integer accessType) {
		this.accessType = accessType;
	}

	public String getUserModuleStyle() {
		return this.userModuleStyle;
	}

	public void setUserModuleStyle(String userModuleStyle) {
		this.userModuleStyle = userModuleStyle;
	}

	public Long getSubgroupId() {
		return this.subgroupId;
	}

	public void setSubgroupId(Long subgroupId) {
		this.subgroupId = subgroupId;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public String getUpdateContent() {
		return this.updateContent;
	}

	public void setUpdateContent(String updateContent) {
		this.updateContent = updateContent;
	}

	public long getContentId() {
		return this.contentId;
	}

	public void setContentId(long contentId) {
		this.contentId = contentId;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public int getContentType() {
		return this.contentType;
	}

	public void setContentType(int contentType) {
		this.contentType = contentType;
	}

	public String getHeadCssAndScript() {
		return this.headCssAndScript;
	}

	public void setHeadCssAndScript(String headCssAndScript) {
		this.headCssAndScript = headCssAndScript;
	}

	public String getBodyCssAndScript() {
		return this.bodyCssAndScript;
	}

	public void setBodyCssAndScript(String bodyCssAndScript) {
		this.bodyCssAndScript = bodyCssAndScript;
	}

	public String getUnCheckPaths() {
		return this.unCheckPaths;
	}

	public void setUnCheckPaths(String unCheckPaths) {
		this.unCheckPaths = unCheckPaths;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModuleInfoShowViewId))
			return false;
		ModuleInfoShowViewId castOther = (ModuleInfoShowViewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getWebsiteName() == castOther.getWebsiteName()) || (this
						.getWebsiteName() != null
						&& castOther.getWebsiteName() != null && this
						.getWebsiteName().equals(castOther.getWebsiteName())))
				&& ((this.getUserModuleName() == castOther.getUserModuleName()) || (this
						.getUserModuleName() != null
						&& castOther.getUserModuleName() != null && this
						.getUserModuleName().equals(
								castOther.getUserModuleName())))
				&& ((this.getUpdateTime() == castOther.getUpdateTime()) || (this
						.getUpdateTime() != null
						&& castOther.getUpdateTime() != null && this
						.getUpdateTime().equals(castOther.getUpdateTime())))
				&& ((this.getWebAddress() == castOther.getWebAddress()) || (this
						.getWebAddress() != null
						&& castOther.getWebAddress() != null && this
						.getWebAddress().equals(castOther.getWebAddress())))
				&& (this.getUserModuleId() == castOther.getUserModuleId())
				&& ((this.getAccessType() == castOther.getAccessType()) || (this
						.getAccessType() != null
						&& castOther.getAccessType() != null && this
						.getAccessType().equals(castOther.getAccessType())))
				&& ((this.getUserModuleStyle() == castOther
						.getUserModuleStyle()) || (this.getUserModuleStyle() != null
						&& castOther.getUserModuleStyle() != null && this
						.getUserModuleStyle().equals(
								castOther.getUserModuleStyle())))
				&& ((this.getSubgroupId() == castOther.getSubgroupId()) || (this
						.getSubgroupId() != null
						&& castOther.getSubgroupId() != null && this
						.getSubgroupId().equals(castOther.getSubgroupId())))
				&& (this.getEnable() == castOther.getEnable())
				&& ((this.getUpdateContent() == castOther.getUpdateContent()) || (this
						.getUpdateContent() != null
						&& castOther.getUpdateContent() != null && this
						.getUpdateContent()
						.equals(castOther.getUpdateContent())))
				&& (this.getContentId() == castOther.getContentId())
				&& (this.getModuleId() == castOther.getModuleId())
				&& (this.getContentType() == castOther.getContentType())
				&& ((this.getHeadCssAndScript() == castOther
						.getHeadCssAndScript()) || (this.getHeadCssAndScript() != null
						&& castOther.getHeadCssAndScript() != null && this
						.getHeadCssAndScript().equals(
								castOther.getHeadCssAndScript())))
				&& ((this.getBodyCssAndScript() == castOther
						.getBodyCssAndScript()) || (this.getBodyCssAndScript() != null
						&& castOther.getBodyCssAndScript() != null && this
						.getBodyCssAndScript().equals(
								castOther.getBodyCssAndScript())))
				&& ((this.getUnCheckPaths() == castOther.getUnCheckPaths()) || (this
						.getUnCheckPaths() != null
						&& castOther.getUnCheckPaths() != null && this
						.getUnCheckPaths().equals(castOther.getUnCheckPaths())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37
				* result
				+ (getWebsiteName() == null ? 0 : this.getWebsiteName()
						.hashCode());
		result = 37
				* result
				+ (getUserModuleName() == null ? 0 : this.getUserModuleName()
						.hashCode());
		result = 37
				* result
				+ (getUpdateTime() == null ? 0 : this.getUpdateTime()
						.hashCode());
		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		result = 37 * result + (int) this.getUserModuleId();
		result = 37
				* result
				+ (getAccessType() == null ? 0 : this.getAccessType()
						.hashCode());
		result = 37
				* result
				+ (getUserModuleStyle() == null ? 0 : this.getUserModuleStyle()
						.hashCode());
		result = 37
				* result
				+ (getSubgroupId() == null ? 0 : this.getSubgroupId()
						.hashCode());
		result = 37 * result + this.getEnable();
		result = 37
				* result
				+ (getUpdateContent() == null ? 0 : this.getUpdateContent()
						.hashCode());
		result = 37 * result + (int) this.getContentId();
		result = 37 * result + (int) this.getModuleId();
		result = 37 * result + this.getContentType();
		result = 37
				* result
				+ (getHeadCssAndScript() == null ? 0 : this
						.getHeadCssAndScript().hashCode());
		result = 37
				* result
				+ (getBodyCssAndScript() == null ? 0 : this
						.getBodyCssAndScript().hashCode());
		result = 37
				* result
				+ (getUnCheckPaths() == null ? 0 : this.getUnCheckPaths()
						.hashCode());
		return result;
	}

	public void setIgnoreByUser(int ignoreByUser) {
		this.ignoreByUser = ignoreByUser;
	}

	public int getIgnoreByUser() {
		return ignoreByUser;
	}

}
