package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kingway.util.OnlineFocus;

/**
 * MonitorWebInfo generated by hbm2java
 */
public class MonitorWebInfo implements java.io.Serializable {

	SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss"); 
	private Long webId;
	private String webAddress;
	private Date monitorFrequency = sdf.parse(OnlineFocus.DEFAULT_TIME,new ParsePosition(0));
	private Date lastMonitorTime = new Date();
	private boolean isMonitoring;
	private int failTimes;
	private long userCount = 1;
	private int enable = 1;
	private Date retryMonitorTime = sdf.parse(OnlineFocus.DEFAULT_TIME,new ParsePosition(0));
	private String headCssAndScript;
	private String bodyCssAndScript;
	private Set<ModuleInfo> moduleInfos = new HashSet<ModuleInfo>(0);
    private int totalMonitorTimes=0;
	public MonitorWebInfo() {
	}

	public MonitorWebInfo(String webAddress, Date monitorFrequency,
			Date lastMonitorTime, boolean isMonitoring, int failTimes,
			long userCount, int enable, Date retryMonitorTime) {
		this.webAddress = webAddress;
		this.monitorFrequency = monitorFrequency;
		this.lastMonitorTime = lastMonitorTime;
		this.isMonitoring = isMonitoring;
		this.failTimes = failTimes;
		this.userCount = userCount;
		this.enable = enable;
		this.retryMonitorTime = retryMonitorTime;
	}

	public MonitorWebInfo(String webAddress, Date monitorFrequency,
			Date lastMonitorTime, boolean isMonitoring, int failTimes,
			long userCount, int enable, Date retryMonitorTime,
			String headCssAndScript, String bodyCssAndScript,
			Set<ModuleInfo> moduleInfos) {
		this.webAddress = webAddress;
		this.monitorFrequency = monitorFrequency;
		this.lastMonitorTime = lastMonitorTime;
		this.isMonitoring = isMonitoring;
		this.failTimes = failTimes;
		this.userCount = userCount;
		this.enable = enable;
		this.retryMonitorTime = retryMonitorTime;
		this.headCssAndScript = headCssAndScript;
		this.bodyCssAndScript = bodyCssAndScript;
		this.moduleInfos = moduleInfos;
	}

	public Long getWebId() {
		return this.webId;
	}

	public void setWebId(Long webId) {
		this.webId = webId;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public Date getMonitorFrequency() {
		return this.monitorFrequency;
	}

	public void setMonitorFrequency(Date monitorFrequency) {
		this.monitorFrequency = monitorFrequency;
	}

	public Date getLastMonitorTime() {
		return this.lastMonitorTime;
	}

	public void setLastMonitorTime(Date lastMonitorTime) {
		this.lastMonitorTime = lastMonitorTime;
	}

	public boolean isIsMonitoring() {
		return this.isMonitoring;
	}

	public void setIsMonitoring(boolean isMonitoring) {
		this.isMonitoring = isMonitoring;
	}

	public int getFailTimes() {
		return this.failTimes;
	}

	public void setFailTimes(int failTimes) {
		this.failTimes = failTimes;
	}

	public long getUserCount() {
		return this.userCount;
	}

	public void setUserCount(long userCount) {
		this.userCount = userCount;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public Date getRetryMonitorTime() {
		return this.retryMonitorTime;
	}

	public void setRetryMonitorTime(Date retryMonitorTime) {
		this.retryMonitorTime = retryMonitorTime;
	}

	public String getHeadCssAndScript() {
		return this.headCssAndScript;
	}

	public void setHeadCssAndScript(String headCssAndScript) {
		this.headCssAndScript = headCssAndScript;
	}

	public String getBodyCssAndScript() {
		return this.bodyCssAndScript;
	}

	public void setBodyCssAndScript(String bodyCssAndScript) {
		this.bodyCssAndScript = bodyCssAndScript;
	}

	public Set<ModuleInfo> getModuleInfos() {
		return this.moduleInfos;
	}

	public void setModuleInfos(Set<ModuleInfo> moduleInfos) {
		this.moduleInfos = moduleInfos;
	}

	public void setTotalMonitorTimes(int totalMonitorTimes) {
		this.totalMonitorTimes = totalMonitorTimes;
	}

	public int getTotalMonitorTimes() {
		return totalMonitorTimes;
	}

}
