package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * MonitorByJsView generated by hbm2java
 */
public class MonitorByJsView implements java.io.Serializable {

	private MonitorByJsViewId id;

	public MonitorByJsView() {
	}

	public MonitorByJsView(MonitorByJsViewId id) {
		this.id = id;
	}

	public MonitorByJsViewId getId() {
		return this.id;
	}

	public void setId(MonitorByJsViewId id) {
		this.id = id;
	}

}
