package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * ReceiverView generated by hbm2java
 */
public class ReceiverView implements java.io.Serializable {

	private ReceiverViewId id;

	public ReceiverView() {
	}

	public ReceiverView(ReceiverViewId id) {
		this.id = id;
	}

	public ReceiverViewId getId() {
		return this.id;
	}

	public void setId(ReceiverViewId id) {
		this.id = id;
	}

}
