package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * ReceiverViewId generated by hbm2java
 */
public class ReceiverViewId implements java.io.Serializable {

	private long userModuleId;
	private long moduleId;
	private Integer monitorType;
	private int receiveType;

	public ReceiverViewId() {
	}

	public ReceiverViewId(long userModuleId, long moduleId, int receiveType) {
		this.userModuleId = userModuleId;
		this.moduleId = moduleId;
		this.receiveType = receiveType;
	}

	public ReceiverViewId(long userModuleId, long moduleId,
			Integer monitorType, int receiveType) {
		this.userModuleId = userModuleId;
		this.moduleId = moduleId;
		this.monitorType = monitorType;
		this.receiveType = receiveType;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public Integer getMonitorType() {
		return this.monitorType;
	}

	public void setMonitorType(Integer monitorType) {
		this.monitorType = monitorType;
	}

	public int getReceiveType() {
		return this.receiveType;
	}

	public void setReceiveType(int receiveType) {
		this.receiveType = receiveType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReceiverViewId))
			return false;
		ReceiverViewId castOther = (ReceiverViewId) other;

		return (this.getUserModuleId() == castOther.getUserModuleId())
				&& (this.getModuleId() == castOther.getModuleId())
				&& ((this.getMonitorType() == castOther.getMonitorType()) || (this
						.getMonitorType() != null
						&& castOther.getMonitorType() != null && this
						.getMonitorType().equals(castOther.getMonitorType())))
				&& (this.getReceiveType() == castOther.getReceiveType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserModuleId();
		result = 37 * result + (int) this.getModuleId();
		result = 37
				* result
				+ (getMonitorType() == null ? 0 : this.getMonitorType()
						.hashCode());
		result = 37 * result + this.getReceiveType();
		return result;
	}

}
