package com.kingway.model;

// Generated 2010-10-24 10:03:09 by Hibernate Tools 3.3.0.GA

/**
 * UserModuleHistoryView generated by hbm2java
 */
public class UserModuleHistoryView implements java.io.Serializable {

	private UserModuleHistoryViewId id;

	public UserModuleHistoryView() {
	}

	public UserModuleHistoryView(UserModuleHistoryViewId id) {
		this.id = id;
	}

	public UserModuleHistoryViewId getId() {
		return this.id;
	}

	public void setId(UserModuleHistoryViewId id) {
		this.id = id;
	}

}
