package com.kingway.model;

// Generated 2010-10-17 13:33:04 by Hibernate Tools 3.3.0.GA

/**
 * UserSpaceModuleInfoShowViewId generated by hbm2java
 */
public class UserSpaceModuleInfoShowViewId implements java.io.Serializable {

	private long userId;
	private String websiteName;
	private String userModuleName;
	private String webAddress;
	private long userModuleId;
	private Integer accessType;
	private String userModuleStyle;
	private Long subgroupId;
	private int enable;
	private long moduleId;
	private String headCssAndScript;
	private String bodyCssAndScript;
	private String unCheckPaths;
	private String updateContent;

	public UserSpaceModuleInfoShowViewId() {
	}

	public UserSpaceModuleInfoShowViewId(long userId, String websiteName,
			String userModuleName, String webAddress, long userModuleId,
			int enable, long moduleId, String updateContent) {
		this.userId = userId;
		this.websiteName = websiteName;
		this.userModuleName = userModuleName;
		this.webAddress = webAddress;
		this.userModuleId = userModuleId;
		this.enable = enable;
		this.moduleId = moduleId;
		this.updateContent = updateContent;
	}

	public UserSpaceModuleInfoShowViewId(long userId, String websiteName,
			String userModuleName, String webAddress, long userModuleId,
			Integer accessType, String userModuleStyle, Long subgroupId,
			int enable, long moduleId, String headCssAndScript,
			String bodyCssAndScript, String unCheckPaths, String updateContent) {
		this.userId = userId;
		this.websiteName = websiteName;
		this.userModuleName = userModuleName;
		this.webAddress = webAddress;
		this.userModuleId = userModuleId;
		this.accessType = accessType;
		this.userModuleStyle = userModuleStyle;
		this.subgroupId = subgroupId;
		this.enable = enable;
		this.moduleId = moduleId;
		this.headCssAndScript = headCssAndScript;
		this.bodyCssAndScript = bodyCssAndScript;
		this.unCheckPaths = unCheckPaths;
		this.updateContent = updateContent;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getWebsiteName() {
		return this.websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public String getUserModuleName() {
		return this.userModuleName;
	}

	public void setUserModuleName(String userModuleName) {
		this.userModuleName = userModuleName;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public Integer getAccessType() {
		return this.accessType;
	}

	public void setAccessType(Integer accessType) {
		this.accessType = accessType;
	}

	public String getUserModuleStyle() {
		return this.userModuleStyle;
	}

	public void setUserModuleStyle(String userModuleStyle) {
		this.userModuleStyle = userModuleStyle;
	}

	public Long getSubgroupId() {
		return this.subgroupId;
	}

	public void setSubgroupId(Long subgroupId) {
		this.subgroupId = subgroupId;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public String getHeadCssAndScript() {
		return this.headCssAndScript;
	}

	public void setHeadCssAndScript(String headCssAndScript) {
		this.headCssAndScript = headCssAndScript;
	}

	public String getBodyCssAndScript() {
		return this.bodyCssAndScript;
	}

	public void setBodyCssAndScript(String bodyCssAndScript) {
		this.bodyCssAndScript = bodyCssAndScript;
	}

	public String getUnCheckPaths() {
		return this.unCheckPaths;
	}

	public void setUnCheckPaths(String unCheckPaths) {
		this.unCheckPaths = unCheckPaths;
	}

	public String getUpdateContent() {
		return this.updateContent;
	}

	public void setUpdateContent(String updateContent) {
		this.updateContent = updateContent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserSpaceModuleInfoShowViewId))
			return false;
		UserSpaceModuleInfoShowViewId castOther = (UserSpaceModuleInfoShowViewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getWebsiteName() == castOther.getWebsiteName()) || (this
						.getWebsiteName() != null
						&& castOther.getWebsiteName() != null && this
						.getWebsiteName().equals(castOther.getWebsiteName())))
				&& ((this.getUserModuleName() == castOther.getUserModuleName()) || (this
						.getUserModuleName() != null
						&& castOther.getUserModuleName() != null && this
						.getUserModuleName().equals(
								castOther.getUserModuleName())))
				&& ((this.getWebAddress() == castOther.getWebAddress()) || (this
						.getWebAddress() != null
						&& castOther.getWebAddress() != null && this
						.getWebAddress().equals(castOther.getWebAddress())))
				&& (this.getUserModuleId() == castOther.getUserModuleId())
				&& ((this.getAccessType() == castOther.getAccessType()) || (this
						.getAccessType() != null
						&& castOther.getAccessType() != null && this
						.getAccessType().equals(castOther.getAccessType())))
				&& ((this.getUserModuleStyle() == castOther
						.getUserModuleStyle()) || (this.getUserModuleStyle() != null
						&& castOther.getUserModuleStyle() != null && this
						.getUserModuleStyle().equals(
								castOther.getUserModuleStyle())))
				&& ((this.getSubgroupId() == castOther.getSubgroupId()) || (this
						.getSubgroupId() != null
						&& castOther.getSubgroupId() != null && this
						.getSubgroupId().equals(castOther.getSubgroupId())))
				&& (this.getEnable() == castOther.getEnable())
				&& (this.getModuleId() == castOther.getModuleId())
				&& ((this.getHeadCssAndScript() == castOther
						.getHeadCssAndScript()) || (this.getHeadCssAndScript() != null
						&& castOther.getHeadCssAndScript() != null && this
						.getHeadCssAndScript().equals(
								castOther.getHeadCssAndScript())))
				&& ((this.getBodyCssAndScript() == castOther
						.getBodyCssAndScript()) || (this.getBodyCssAndScript() != null
						&& castOther.getBodyCssAndScript() != null && this
						.getBodyCssAndScript().equals(
								castOther.getBodyCssAndScript())))
				&& ((this.getUnCheckPaths() == castOther.getUnCheckPaths()) || (this
						.getUnCheckPaths() != null
						&& castOther.getUnCheckPaths() != null && this
						.getUnCheckPaths().equals(castOther.getUnCheckPaths())))
				&& ((this.getUpdateContent() == castOther.getUpdateContent()) || (this
						.getUpdateContent() != null
						&& castOther.getUpdateContent() != null && this
						.getUpdateContent()
						.equals(castOther.getUpdateContent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37
				* result
				+ (getWebsiteName() == null ? 0 : this.getWebsiteName()
						.hashCode());
		result = 37
				* result
				+ (getUserModuleName() == null ? 0 : this.getUserModuleName()
						.hashCode());
		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		result = 37 * result + (int) this.getUserModuleId();
		result = 37
				* result
				+ (getAccessType() == null ? 0 : this.getAccessType()
						.hashCode());
		result = 37
				* result
				+ (getUserModuleStyle() == null ? 0 : this.getUserModuleStyle()
						.hashCode());
		result = 37
				* result
				+ (getSubgroupId() == null ? 0 : this.getSubgroupId()
						.hashCode());
		result = 37 * result + this.getEnable();
		result = 37 * result + (int) this.getModuleId();
		result = 37
				* result
				+ (getHeadCssAndScript() == null ? 0 : this
						.getHeadCssAndScript().hashCode());
		result = 37
				* result
				+ (getBodyCssAndScript() == null ? 0 : this
						.getBodyCssAndScript().hashCode());
		result = 37
				* result
				+ (getUnCheckPaths() == null ? 0 : this.getUnCheckPaths()
						.hashCode());
		result = 37
				* result
				+ (getUpdateContent() == null ? 0 : this.getUpdateContent()
						.hashCode());
		return result;
	}

}
