package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * UserSpaceInfo generated by hbm2java
 */
public class UserSpaceInfo implements java.io.Serializable {

	private Long userSpaceId;
	private UserInfo userInfo;
	private int accessType;
	private String question;
	private String answer;
	private String userSpaceName;
	private Long totalAccesses = 0L;
	private String userImage = "";
	private String userSpaceStyle="bgColor:rgb(200, 132, 132);cssFile:/personalfocus/css/userindexcss/themeSunflower.css;linkColor:rgb(85, 26, 139);navColor:rgb(241, 233, 233);moduleColor:rgb(244, 241, 241);";

	public UserSpaceInfo() {
	}

	public UserSpaceInfo(UserInfo userInfo, int accessType,
			String userSpaceStyle) {
		this.userInfo = userInfo;
		this.accessType = accessType;
		this.userSpaceStyle = userSpaceStyle;
	}

	public UserSpaceInfo(UserInfo userInfo, int accessType, String question,
			String answer, String userSpaceName, Long totalAccesses,
			String userImage, String userSpaceStyle) {
		this.userInfo = userInfo;
		this.accessType = accessType;
		this.question = question;
		this.answer = answer;
		this.userSpaceName = userSpaceName;
		this.totalAccesses = totalAccesses;
		this.userImage = userImage;
		this.userSpaceStyle = userSpaceStyle;
	}

	public Long getUserSpaceId() {
		return this.userSpaceId;
	}

	public void setUserSpaceId(Long userSpaceId) {
		this.userSpaceId = userSpaceId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public int getAccessType() {
		return this.accessType;
	}

	public void setAccessType(int accessType) {
		this.accessType = accessType;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getUserSpaceName() {
		return this.userSpaceName;
	}

	public void setUserSpaceName(String userSpaceName) {
		this.userSpaceName = userSpaceName;
	}

	public Long getTotalAccesses() {
		return this.totalAccesses;
	}

	public void setTotalAccesses(Long totalAccesses) {
		this.totalAccesses = totalAccesses;
	}

	public String getUserImage() {
		return this.userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	public String getUserSpaceStyle() {
		return this.userSpaceStyle;
	}

	public void setUserSpaceStyle(String userSpaceStyle) {
		this.userSpaceStyle = userSpaceStyle;
	}

}
  