package com.kingway.model;

// Generated 2010-12-9 22:12:03 by Hibernate Tools 3.3.0.GA

/**
 * UserModuleUpdatepathsView generated by hbm2java
 */
public class UserModuleUpdatepathsView implements java.io.Serializable {

	private UserModuleUpdatepathsViewId id;

	public UserModuleUpdatepathsView() {
	}

	public UserModuleUpdatepathsView(UserModuleUpdatepathsViewId id) {
		this.id = id;
	}

	public UserModuleUpdatepathsViewId getId() {
		return this.id;
	}

	public void setId(UserModuleUpdatepathsViewId id) {
		this.id = id;
	}

}
