package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * UserActivecode generated by hbm2java
 */
public class UserActivecode implements java.io.Serializable {

	private Long activeCodeId;
	private UserInfo userInfo;
	private String activeCode;
	private Date activeCodeSendTime;

	public UserActivecode() {
	}

	public UserActivecode(UserInfo userInfo, String activeCode,
			Date activeCodeSendTime) {
		this.userInfo = userInfo;
		this.activeCode = activeCode;
		this.activeCodeSendTime = activeCodeSendTime;
	}

	public Long getActiveCodeId() {
		return this.activeCodeId;
	}

	public void setActiveCodeId(Long activeCodeId) {
		this.activeCodeId = activeCodeId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public String getActiveCode() {
		return this.activeCode;
	}

	public void setActiveCode(String activeCode) {
		this.activeCode = activeCode;
	}

	public Date getActiveCodeSendTime() {
		return this.activeCodeSendTime;
	}

	public void setActiveCodeSendTime(Date activeCodeSendTime) {
		this.activeCodeSendTime = activeCodeSendTime;
	}

}
