package com.kingway.model;

// Generated 2010-10-24 10:03:09 by Hibernate Tools 3.3.0.GA

/**
 * UserModuleHistoryListView generated by hbm2java
 */
public class UserModuleHistoryListView implements java.io.Serializable {

	private UserModuleHistoryListViewId id;

	public UserModuleHistoryListView() {
	}

	public UserModuleHistoryListView(UserModuleHistoryListViewId id) {
		this.id = id;
	}

	public UserModuleHistoryListViewId getId() {
		return this.id;
	}

	public void setId(UserModuleHistoryListViewId id) {
		this.id = id;
	}

}
