package com.kingway.model;

// Generated 2010-10-18 22:22:50 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * UserModuleContents generated by hbm2java
 */
public class UserModuleContents implements java.io.Serializable {

	private Long contentId;
	private String userModuleContent;
	private long userModuleId;
	private Date updateTime;
	private int contentType;
	private int alreadySendMessage;
	private int alreadySendMail;
	private int ignoreByUser;

	public UserModuleContents() {
	}

	public UserModuleContents(String userModuleContent, long userModuleId,
			Date updateTime, int contentType, int alreadySendMessage,
			int alreadySendMail, int ignoreByUser) {
		this.userModuleContent = userModuleContent;
		this.userModuleId = userModuleId;
		this.updateTime = updateTime;
		this.contentType = contentType;
		this.alreadySendMessage = alreadySendMessage;
		this.alreadySendMail = alreadySendMail;
		this.ignoreByUser = ignoreByUser;
	}

	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}

	public String getUserModuleContent() {
		return this.userModuleContent;
	}

	public void setUserModuleContent(String userModuleContent) {
		this.userModuleContent = userModuleContent;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getContentType() {
		return this.contentType;
	}

	public void setContentType(int contentType) {
		this.contentType = contentType;
	}

	public int getAlreadySendMessage() {
		return this.alreadySendMessage;
	}

	public void setAlreadySendMessage(int alreadySendMessage) {
		this.alreadySendMessage = alreadySendMessage;
	}

	public int getAlreadySendMail() {
		return this.alreadySendMail;
	}

	public void setAlreadySendMail(int alreadySendMail) {
		this.alreadySendMail = alreadySendMail;
	}

	public int getIgnoreByUser() {
		return this.ignoreByUser;
	}

	public void setIgnoreByUser(int ignoreByUser) {
		this.ignoreByUser = ignoreByUser;
	}

}
