package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * UserSubscribe generated by hbm2java
 */
public class UserSubscribe implements java.io.Serializable {

	private Long subscribeId;
	private UserInfo userInfoBySubscribeUserId;
	private UserInfo userInfoByUserId;

	public UserSubscribe() {
	}

	public UserSubscribe(UserInfo userInfoBySubscribeUserId,
			UserInfo userInfoByUserId) {
		this.userInfoBySubscribeUserId = userInfoBySubscribeUserId;
		this.userInfoByUserId = userInfoByUserId;
	}

	public Long getSubscribeId() {
		return this.subscribeId;
	}

	public void setSubscribeId(Long subscribeId) {
		this.subscribeId = subscribeId;
	}

	public UserInfo getUserInfoBySubscribeUserId() {
		return this.userInfoBySubscribeUserId;
	}

	public void setUserInfoBySubscribeUserId(UserInfo userInfoBySubscribeUserId) {
		this.userInfoBySubscribeUserId = userInfoBySubscribeUserId;
	}

	public UserInfo getUserInfoByUserId() {
		return this.userInfoByUserId;
	}

	public void setUserInfoByUserId(UserInfo userInfoByUserId) {
		this.userInfoByUserId = userInfoByUserId;
	}

}
