package com.kingway.model;

// Generated 2010-10-24 10:03:09 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * UserModuleHistoryViewId generated by hbm2java
 */
public class UserModuleHistoryViewId implements java.io.Serializable {

	private String userModuleStyle;
	private String headCssAndScript;
	private String bodyCssAndScript;
	private Date updateTime;
	private String content;
	private long bufferId;
	private long userModuleId;

	public UserModuleHistoryViewId() {
	}

	public UserModuleHistoryViewId(Date updateTime, String content,
			long bufferId, long userModuleId) {
		this.updateTime = updateTime;
		this.content = content;
		this.bufferId = bufferId;
		this.userModuleId = userModuleId;
	}

	public UserModuleHistoryViewId(String userModuleStyle,
			String headCssAndScript, String bodyCssAndScript, Date updateTime,
			String content, long bufferId, long userModuleId) {
		this.userModuleStyle = userModuleStyle;
		this.headCssAndScript = headCssAndScript;
		this.bodyCssAndScript = bodyCssAndScript;
		this.updateTime = updateTime;
		this.content = content;
		this.bufferId = bufferId;
		this.userModuleId = userModuleId;
	}

	public String getUserModuleStyle() {
		return this.userModuleStyle;
	}

	public void setUserModuleStyle(String userModuleStyle) {
		this.userModuleStyle = userModuleStyle;
	}

	public String getHeadCssAndScript() {
		return this.headCssAndScript;
	}

	public void setHeadCssAndScript(String headCssAndScript) {
		this.headCssAndScript = headCssAndScript;
	}

	public String getBodyCssAndScript() {
		return this.bodyCssAndScript;
	}

	public void setBodyCssAndScript(String bodyCssAndScript) {
		this.bodyCssAndScript = bodyCssAndScript;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public long getBufferId() {
		return this.bufferId;
	}

	public void setBufferId(long bufferId) {
		this.bufferId = bufferId;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserModuleHistoryViewId))
			return false;
		UserModuleHistoryViewId castOther = (UserModuleHistoryViewId) other;

		return ((this.getUserModuleStyle() == castOther.getUserModuleStyle()) || (this
				.getUserModuleStyle() != null
				&& castOther.getUserModuleStyle() != null && this
				.getUserModuleStyle().equals(castOther.getUserModuleStyle())))
				&& ((this.getHeadCssAndScript() == castOther
						.getHeadCssAndScript()) || (this.getHeadCssAndScript() != null
						&& castOther.getHeadCssAndScript() != null && this
						.getHeadCssAndScript().equals(
								castOther.getHeadCssAndScript())))
				&& ((this.getBodyCssAndScript() == castOther
						.getBodyCssAndScript()) || (this.getBodyCssAndScript() != null
						&& castOther.getBodyCssAndScript() != null && this
						.getBodyCssAndScript().equals(
								castOther.getBodyCssAndScript())))
				&& ((this.getUpdateTime() == castOther.getUpdateTime()) || (this
						.getUpdateTime() != null
						&& castOther.getUpdateTime() != null && this
						.getUpdateTime().equals(castOther.getUpdateTime())))
				&& ((this.getContent() == castOther.getContent()) || (this
						.getContent() != null
						&& castOther.getContent() != null && this.getContent()
						.equals(castOther.getContent())))
				&& (this.getBufferId() == castOther.getBufferId())
				&& (this.getUserModuleId() == castOther.getUserModuleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUserModuleStyle() == null ? 0 : this.getUserModuleStyle()
						.hashCode());
		result = 37
				* result
				+ (getHeadCssAndScript() == null ? 0 : this
						.getHeadCssAndScript().hashCode());
		result = 37
				* result
				+ (getBodyCssAndScript() == null ? 0 : this
						.getBodyCssAndScript().hashCode());
		result = 37
				* result
				+ (getUpdateTime() == null ? 0 : this.getUpdateTime()
						.hashCode());
		result = 37 * result
				+ (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result + (int) this.getBufferId();
		result = 37 * result + (int) this.getUserModuleId();
		return result;
	}

}
