package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Long userId;
	private String userName;
	private String gender = "ÄÐ";
	private Date birthday;
	private String password;
	private String mailbox;
	private String phone;
	private Date registrationTime = new Date();
	private int enable = 1;
	private Integer userType = 0;
	private Integer userPoint = 0;
	private Set<UserSubscribe> userSubscribesForSubscribeUserId = new HashSet<UserSubscribe>(
			0);
	private Set<UserDefaultReceiveInfo> userDefaultReceiveInfos = new HashSet<UserDefaultReceiveInfo>(
			0);
	private Set<UserSubscribe> userSubscribesForUserId = new HashSet<UserSubscribe>(
			0);
	private Set<UserSpaceInfo> userSpaceInfos = new HashSet<UserSpaceInfo>(0);
	private Set<UserActivecode> userActivecodes = new HashSet<UserActivecode>(0);
	private Set<UserModuleInfo> userModuleInfos = new HashSet<UserModuleInfo>(0);
	private Set<UserModuleSubgroupInfo> userModuleSubgroupInfos = new HashSet<UserModuleSubgroupInfo>(
			0);

	public UserInfo() {
	}

	public UserInfo(String userName, String password, Date registrationTime,
			int enable) {
		this.userName = userName;
		this.password = password;
		this.registrationTime = registrationTime;
		this.enable = enable;
	}

	public UserInfo(String userName, String gender, Date birthday,
			String password, String mailbox, String phone,
			Date registrationTime, int enable, Integer userType,
			Integer userPoint,
			Set<UserSubscribe> userSubscribesForSubscribeUserId,
			Set<UserDefaultReceiveInfo> userDefaultReceiveInfos,
			Set<UserSubscribe> userSubscribesForUserId,
			Set<UserSpaceInfo> userSpaceInfos,
			Set<UserActivecode> userActivecodes,
			Set<UserModuleInfo> userModuleInfos,
			Set<UserModuleSubgroupInfo> userModuleSubgroupInfos) {
		this.userName = userName;
		this.gender = gender;
		this.birthday = birthday;
		this.password = password;
		this.mailbox = mailbox;
		this.phone = phone;
		this.registrationTime = registrationTime;
		this.enable = enable;
		this.userType = userType;
		this.userPoint = userPoint;
		this.userSubscribesForSubscribeUserId = userSubscribesForSubscribeUserId;
		this.userDefaultReceiveInfos = userDefaultReceiveInfos;
		this.userSubscribesForUserId = userSubscribesForUserId;
		this.userSpaceInfos = userSpaceInfos;
		this.userActivecodes = userActivecodes;
		this.userModuleInfos = userModuleInfos;
		this.userModuleSubgroupInfos = userModuleSubgroupInfos;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMailbox() {
		return this.mailbox;
	}

	public void setMailbox(String mailbox) {
		this.mailbox = mailbox;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getRegistrationTime() {
		return this.registrationTime;
	}

	public void setRegistrationTime(Date registrationTime) {
		this.registrationTime = registrationTime;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public Integer getUserPoint() {
		return this.userPoint;
	}

	public void setUserPoint(Integer userPoint) {
		this.userPoint = userPoint;
	}

	public Set<UserSubscribe> getUserSubscribesForSubscribeUserId() {
		return this.userSubscribesForSubscribeUserId;
	}

	public void setUserSubscribesForSubscribeUserId(
			Set<UserSubscribe> userSubscribesForSubscribeUserId) {
		this.userSubscribesForSubscribeUserId = userSubscribesForSubscribeUserId;
	}

	public Set<UserDefaultReceiveInfo> getUserDefaultReceiveInfos() {
		return this.userDefaultReceiveInfos;
	}

	public void setUserDefaultReceiveInfos(
			Set<UserDefaultReceiveInfo> userDefaultReceiveInfos) {
		this.userDefaultReceiveInfos = userDefaultReceiveInfos;
	}

	public Set<UserSubscribe> getUserSubscribesForUserId() {
		return this.userSubscribesForUserId;
	}

	public void setUserSubscribesForUserId(
			Set<UserSubscribe> userSubscribesForUserId) {
		this.userSubscribesForUserId = userSubscribesForUserId;
	}

	public Set<UserSpaceInfo> getUserSpaceInfos() {
		return this.userSpaceInfos;
	}

	public void setUserSpaceInfos(Set<UserSpaceInfo> userSpaceInfos) {
		this.userSpaceInfos = userSpaceInfos;
	}

	public Set<UserActivecode> getUserActivecodes() {
		return this.userActivecodes;
	}

	public void setUserActivecodes(Set<UserActivecode> userActivecodes) {
		this.userActivecodes = userActivecodes;
	}

	public Set<UserModuleInfo> getUserModuleInfos() {
		return this.userModuleInfos;
	}

	public void setUserModuleInfos(Set<UserModuleInfo> userModuleInfos) {
		this.userModuleInfos = userModuleInfos;
	}

	public Set<UserModuleSubgroupInfo> getUserModuleSubgroupInfos() {
		return this.userModuleSubgroupInfos;
	}

	public void setUserModuleSubgroupInfos(
			Set<UserModuleSubgroupInfo> userModuleSubgroupInfos) {
		this.userModuleSubgroupInfos = userModuleSubgroupInfos;
	}

}
