package com.kingway.model;

// Generated 2010-10-17 13:33:04 by Hibernate Tools 3.3.0.GA

/**
 * UserSpaceModuleInfoShowView generated by hbm2java
 */
public class UserSpaceModuleInfoShowView implements java.io.Serializable {

	private UserSpaceModuleInfoShowViewId id;

	public UserSpaceModuleInfoShowView() {
	}

	public UserSpaceModuleInfoShowView(UserSpaceModuleInfoShowViewId id) {
		this.id = id;
	}

	public UserSpaceModuleInfoShowViewId getId() {
		return this.id;
	}

	public void setId(UserSpaceModuleInfoShowViewId id) {
		this.id = id;
	}

}
