package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * UserReceiveInfo generated by hbm2java
 */
public class UserReceiveInfo implements java.io.Serializable {

	private Long receiveId;
	private UserModuleInfo userModuleInfo;
	private Date startTime;
	private Date stopTime;
	private int receiveType;
	private Date lastSendTime;
	private Date sendFrequency;
	private int maxReceiveNum;

	public UserReceiveInfo() {
	}

	public UserReceiveInfo(UserModuleInfo userModuleInfo, Date startTime,
			Date stopTime, int receiveType, Date lastSendTime,
			Date sendFrequency, int maxReceiveNum) {
		this.userModuleInfo = userModuleInfo;
		this.startTime = startTime;
		this.stopTime = stopTime;
		this.receiveType = receiveType;
		this.lastSendTime = lastSendTime;
		this.sendFrequency = sendFrequency;
		this.maxReceiveNum = maxReceiveNum;
	}

	public Long getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(Long receiveId) {
		this.receiveId = receiveId;
	}

	public UserModuleInfo getUserModuleInfo() {
		return this.userModuleInfo;
	}

	public void setUserModuleInfo(UserModuleInfo userModuleInfo) {
		this.userModuleInfo = userModuleInfo;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getStopTime() {
		return this.stopTime;
	}

	public void setStopTime(Date stopTime) {
		this.stopTime = stopTime;
	}

	public int getReceiveType() {
		return this.receiveType;
	}

	public void setReceiveType(int receiveType) {
		this.receiveType = receiveType;
	}

	public Date getLastSendTime() {
		return this.lastSendTime;
	}

	public void setLastSendTime(Date lastSendTime) {
		this.lastSendTime = lastSendTime;
	}

	public Date getSendFrequency() {
		return this.sendFrequency;
	}

	public void setSendFrequency(Date sendFrequency) {
		this.sendFrequency = sendFrequency;
	}

	public int getMaxReceiveNum() {
		return this.maxReceiveNum;
	}

	public void setMaxReceiveNum(int maxReceiveNum) {
		this.maxReceiveNum = maxReceiveNum;
	}

}
