package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * UsermoduleViewId generated by hbm2java
 */
public class UsermoduleViewId implements java.io.Serializable {

	private long userId;
	private String userModuleName;
	private long moduleId;
	private String websiteName;
	private String webAddress;

	public UsermoduleViewId() {
	}

	public UsermoduleViewId(long userId, String userModuleName, long moduleId,
			String websiteName, String webAddress) {
		this.userId = userId;
		this.userModuleName = userModuleName;
		this.moduleId = moduleId;
		this.websiteName = websiteName;
		this.webAddress = webAddress;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getUserModuleName() {
		return this.userModuleName;
	}

	public void setUserModuleName(String userModuleName) {
		this.userModuleName = userModuleName;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public String getWebsiteName() {
		return this.websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsermoduleViewId))
			return false;
		UsermoduleViewId castOther = (UsermoduleViewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getUserModuleName() == castOther.getUserModuleName()) || (this
						.getUserModuleName() != null
						&& castOther.getUserModuleName() != null && this
						.getUserModuleName().equals(
								castOther.getUserModuleName())))
				&& (this.getModuleId() == castOther.getModuleId())
				&& ((this.getWebsiteName() == castOther.getWebsiteName()) || (this
						.getWebsiteName() != null
						&& castOther.getWebsiteName() != null && this
						.getWebsiteName().equals(castOther.getWebsiteName())))
				&& ((this.getWebAddress() == castOther.getWebAddress()) || (this
						.getWebAddress() != null
						&& castOther.getWebAddress() != null && this
						.getWebAddress().equals(castOther.getWebAddress())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37
				* result
				+ (getUserModuleName() == null ? 0 : this.getUserModuleName()
						.hashCode());
		result = 37 * result + (int) this.getModuleId();
		result = 37
				* result
				+ (getWebsiteName() == null ? 0 : this.getWebsiteName()
						.hashCode());
		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		return result;
	}

}
