package com.kingway.model;

// Generated 2010-10-31 21:55:46 by Hibernate Tools 3.3.0.GA

/**
 * UserFocusWebModuleViewId generated by hbm2java
 */
public class UserFocusWebModuleViewId implements java.io.Serializable {

	private String webAddress;
	private String modulePath;
	private long userModuleId;
	private long userId;

	public UserFocusWebModuleViewId() {
	}

	public UserFocusWebModuleViewId(String webAddress, long userModuleId,
			long userId) {
		this.webAddress = webAddress;
		this.userModuleId = userModuleId;
		this.userId = userId;
	}

	public UserFocusWebModuleViewId(String webAddress, String modulePath,
			long userModuleId, long userId) {
		this.webAddress = webAddress;
		this.modulePath = modulePath;
		this.userModuleId = userModuleId;
		this.userId = userId;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public String getModulePath() {
		return this.modulePath;
	}

	public void setModulePath(String modulePath) {
		this.modulePath = modulePath;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserFocusWebModuleViewId))
			return false;
		UserFocusWebModuleViewId castOther = (UserFocusWebModuleViewId) other;

		return ((this.getWebAddress() == castOther.getWebAddress()) || (this
				.getWebAddress() != null
				&& castOther.getWebAddress() != null && this.getWebAddress()
				.equals(castOther.getWebAddress())))
				&& ((this.getModulePath() == castOther.getModulePath()) || (this
						.getModulePath() != null
						&& castOther.getModulePath() != null && this
						.getModulePath().equals(castOther.getModulePath())))
				&& (this.getUserModuleId() == castOther.getUserModuleId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		result = 37
				* result
				+ (getModulePath() == null ? 0 : this.getModulePath()
						.hashCode());
		result = 37 * result + (int) this.getUserModuleId();
		result = 37 * result + (int) this.getUserId();
		return result;
	}

}
