package com.kingway.model;

// Generated 2010-12-9 22:12:03 by Hibernate Tools 3.3.0.GA

/**
 * UserModuleUpdatepathsViewId generated by hbm2java
 */
public class UserModuleUpdatepathsViewId implements java.io.Serializable {

	private long userId;
	private String webAddress;
	private String modulePath;
	private long contentId;
	private long userModuleId;
	private String userModuleContent;
	private int contentType;
	private String unCheckPaths;

	public UserModuleUpdatepathsViewId() {
	}

	public UserModuleUpdatepathsViewId(long userId, String webAddress,
			long contentId, long userModuleId, String userModuleContent,
			int contentType) {
		this.userId = userId;
		this.webAddress = webAddress;
		this.contentId = contentId;
		this.userModuleId = userModuleId;
		this.userModuleContent = userModuleContent;
		this.contentType = contentType;
	}

	public UserModuleUpdatepathsViewId(long userId, String webAddress,
			String modulePath, long contentId, long userModuleId,
			String userModuleContent, int contentType, String unCheckPaths) {
		this.userId = userId;
		this.webAddress = webAddress;
		this.modulePath = modulePath;
		this.contentId = contentId;
		this.userModuleId = userModuleId;
		this.userModuleContent = userModuleContent;
		this.contentType = contentType;
		this.unCheckPaths = unCheckPaths;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public String getModulePath() {
		return this.modulePath;
	}

	public void setModulePath(String modulePath) {
		this.modulePath = modulePath;
	}

	public long getContentId() {
		return this.contentId;
	}

	public void setContentId(long contentId) {
		this.contentId = contentId;
	}

	public long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public String getUserModuleContent() {
		return this.userModuleContent;
	}

	public void setUserModuleContent(String userModuleContent) {
		this.userModuleContent = userModuleContent;
	}

	public int getContentType() {
		return this.contentType;
	}

	public void setContentType(int contentType) {
		this.contentType = contentType;
	}

	public String getUnCheckPaths() {
		return this.unCheckPaths;
	}

	public void setUnCheckPaths(String unCheckPaths) {
		this.unCheckPaths = unCheckPaths;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserModuleUpdatepathsViewId))
			return false;
		UserModuleUpdatepathsViewId castOther = (UserModuleUpdatepathsViewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getWebAddress() == castOther.getWebAddress()) || (this
						.getWebAddress() != null
						&& castOther.getWebAddress() != null && this
						.getWebAddress().equals(castOther.getWebAddress())))
				&& ((this.getModulePath() == castOther.getModulePath()) || (this
						.getModulePath() != null
						&& castOther.getModulePath() != null && this
						.getModulePath().equals(castOther.getModulePath())))
				&& (this.getContentId() == castOther.getContentId())
				&& (this.getUserModuleId() == castOther.getUserModuleId())
				&& ((this.getUserModuleContent() == castOther
						.getUserModuleContent()) || (this
						.getUserModuleContent() != null
						&& castOther.getUserModuleContent() != null && this
						.getUserModuleContent().equals(
								castOther.getUserModuleContent())))
				&& (this.getContentType() == castOther.getContentType())
				&& ((this.getUnCheckPaths() == castOther.getUnCheckPaths()) || (this
						.getUnCheckPaths() != null
						&& castOther.getUnCheckPaths() != null && this
						.getUnCheckPaths().equals(castOther.getUnCheckPaths())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37
				* result
				+ (getWebAddress() == null ? 0 : this.getWebAddress()
						.hashCode());
		result = 37
				* result
				+ (getModulePath() == null ? 0 : this.getModulePath()
						.hashCode());
		result = 37 * result + (int) this.getContentId();
		result = 37 * result + (int) this.getUserModuleId();
		result = 37
				* result
				+ (getUserModuleContent() == null ? 0 : this
						.getUserModuleContent().hashCode());
		result = 37 * result + this.getContentType();
		result = 37
				* result
				+ (getUnCheckPaths() == null ? 0 : this.getUnCheckPaths()
						.hashCode());
		return result;
	}

}
