package com.kingway.model;

// Generated 2011-1-23 9:52:10 by Hibernate Tools 3.3.0.GA

/**
 * UserFriendsView generated by hbm2java
 */
public class UserFriendsView implements java.io.Serializable {

	private UserFriendsViewId id;

	public UserFriendsView() {
	}

	public UserFriendsView(UserFriendsViewId id) {
		this.id = id;
	}

	public UserFriendsViewId getId() {
		return this.id;
	}

	public void setId(UserFriendsViewId id) {
		this.id = id;
	}

}
