package com.kingway.model;

// Generated 2010-10-27 12:25:43 by Hibernate Tools 3.3.0.GA

/**
 * UserModuleDisingoreViewId generated by hbm2java
 */
public class UserModuleDisingoreViewId implements java.io.Serializable {

	private long userId;
	private long contentId;

	public UserModuleDisingoreViewId() {
	}

	public UserModuleDisingoreViewId(long userId, long contentId) {
		this.userId = userId;
		this.contentId = contentId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getContentId() {
		return this.contentId;
	}

	public void setContentId(long contentId) {
		this.contentId = contentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserModuleDisingoreViewId))
			return false;
		UserModuleDisingoreViewId castOther = (UserModuleDisingoreViewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getContentId() == castOther.getContentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getContentId();
		return result;
	}

}
