package com.kingway.model;

// Generated 2010-10-31 21:55:46 by Hibernate Tools 3.3.0.GA

/**
 * UserFocusWebModuleView generated by hbm2java
 */
public class UserFocusWebModuleView implements java.io.Serializable {

	private UserFocusWebModuleViewId id;

	public UserFocusWebModuleView() {
	}

	public UserFocusWebModuleView(UserFocusWebModuleViewId id) {
		this.id = id;
	}

	public UserFocusWebModuleViewId getId() {
		return this.id;
	}

	public void setId(UserFocusWebModuleViewId id) {
		this.id = id;
	}

}
