package com.kingway.model;

// Generated 2010-10-8 23:39:20 by Hibernate Tools 3.3.0.GA

import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.kingway.util.OnlineFocus;

/**
 * UserModuleInfo generated by hbm2java
 */
public class UserModuleInfo implements java.io.Serializable {

	SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss"); 
	private Long userModuleId;
	private ModuleInfo moduleInfo;
	private UserModuleSubgroupInfo userModuleSubgroupInfo;
	private UserInfo userInfo;
	private String userModuleName = "ÐÂÀ¸Ä¿";
	private String websiteName;
	private int enable = 1;
	private Date monitorFrequency = sdf.parse(OnlineFocus.DEFAULT_TIME,new ParsePosition(0));
	private String userModuleStyle = "position: absolute; left: -1000px; top: -1000px; height: 200px; width: 500px;";
	private Integer accessType = 1;
	private Integer monitorType = 0;
	private String unCheckPaths="null";
	private Set<UserReceiveInfo> userReceiveInfos = new HashSet<UserReceiveInfo>(
			0);
	private Set<ContentReceiver> contentReceivers = new HashSet<ContentReceiver>(
			0);

	public UserModuleInfo() {
	}

	public UserModuleInfo(ModuleInfo moduleInfo, UserInfo userInfo,
			String userModuleName, String websiteName, int enable,
			Date monitorFrequency) {
		this.moduleInfo = moduleInfo;
		this.userInfo = userInfo;
		this.userModuleName = userModuleName;
		this.websiteName = websiteName;
		this.enable = enable;
		this.monitorFrequency = monitorFrequency;
	}

	public UserModuleInfo(ModuleInfo moduleInfo,
			UserModuleSubgroupInfo userModuleSubgroupInfo, UserInfo userInfo,
			String userModuleName, String websiteName, int enable,
			Date monitorFrequency, String userModuleStyle, Integer accessType,
			Integer monitorType, String unCheckPaths,
			Set<UserReceiveInfo> userReceiveInfos,
			Set<ContentReceiver> contentReceivers) {
		this.moduleInfo = moduleInfo;
		this.userModuleSubgroupInfo = userModuleSubgroupInfo;
		this.userInfo = userInfo;
		this.userModuleName = userModuleName;
		this.websiteName = websiteName;
		this.enable = enable;
		this.monitorFrequency = monitorFrequency;
		this.userModuleStyle = userModuleStyle;
		this.accessType = accessType;
		this.monitorType = monitorType;
		this.unCheckPaths = unCheckPaths;
		this.userReceiveInfos = userReceiveInfos;
		this.contentReceivers = contentReceivers;
	}

	public Long getUserModuleId() {
		return this.userModuleId;
	}

	public void setUserModuleId(Long userModuleId) {
		this.userModuleId = userModuleId;
	}

	public ModuleInfo getModuleInfo() {
		return this.moduleInfo;
	}

	public void setModuleInfo(ModuleInfo moduleInfo) {
		this.moduleInfo = moduleInfo;
	}

	public UserModuleSubgroupInfo getUserModuleSubgroupInfo() {
		return this.userModuleSubgroupInfo;
	}

	public void setUserModuleSubgroupInfo(
			UserModuleSubgroupInfo userModuleSubgroupInfo) {
		this.userModuleSubgroupInfo = userModuleSubgroupInfo;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public String getUserModuleName() {
		return this.userModuleName;
	}

	public void setUserModuleName(String userModuleName) {
		this.userModuleName = userModuleName;
	}

	public String getWebsiteName() {
		return this.websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

	public Date getMonitorFrequency() {
		return this.monitorFrequency;
	}

	public void setMonitorFrequency(Date monitorFrequency) {
		this.monitorFrequency = monitorFrequency;
	}

	public String getUserModuleStyle() {
		return this.userModuleStyle;
	}

	public void setUserModuleStyle(String userModuleStyle) {
		this.userModuleStyle = userModuleStyle;
	}

	public Integer getAccessType() {
		return this.accessType;
	}

	public void setAccessType(Integer accessType) {
		this.accessType = accessType;
	}

	public Integer getMonitorType() {
		return this.monitorType;
	}

	public void setMonitorType(Integer monitorType) {
		this.monitorType = monitorType;
	}

	public String getUnCheckPaths() {
		return this.unCheckPaths;
	}

	public void setUnCheckPaths(String unCheckPaths) {
		this.unCheckPaths = unCheckPaths;
	}

	public Set<UserReceiveInfo> getUserReceiveInfos() {
		return this.userReceiveInfos;
	}

	public void setUserReceiveInfos(Set<UserReceiveInfo> userReceiveInfos) {
		this.userReceiveInfos = userReceiveInfos;
	}

	public Set<ContentReceiver> getContentReceivers() {
		return this.contentReceivers;
	}

	public void setContentReceivers(Set<ContentReceiver> contentReceivers) {
		this.contentReceivers = contentReceivers;
	}

}
