package com.kingway.model;

// Generated 2010-10-1 0:21:31 by Hibernate Tools 3.3.0.GA

/**
 * UsermoduleView generated by hbm2java
 */
public class UsermoduleView implements java.io.Serializable {

	private UsermoduleViewId id;

	public UsermoduleView() {
	}

	public UsermoduleView(UsermoduleViewId id) {
		this.id = id;
	}

	public UsermoduleViewId getId() {
		return this.id;
	}

	public void setId(UsermoduleViewId id) {
		this.id = id;
	}

}
