package com.kingway.model;

// Generated 2010-10-27 12:25:43 by Hibernate Tools 3.3.0.GA

/**
 * UserModuleDisingoreView generated by hbm2java
 */
public class UserModuleDisingoreView implements java.io.Serializable {

	private UserModuleDisingoreViewId id;

	public UserModuleDisingoreView() {
	}

	public UserModuleDisingoreView(UserModuleDisingoreViewId id) {
		this.id = id;
	}

	public UserModuleDisingoreViewId getId() {
		return this.id;
	}

	public void setId(UserModuleDisingoreViewId id) {
		this.id = id;
	}

}
